spring.application.name=photo-management-system
spring.session.store-type=none

spring.datasource.url=jdbc:postgresql://localhost:5432/photo_management
spring.datasource.username=postgres
spring.datasource.password=030308
spring.datasource.driver-class-name=org.postgresql.Driver