# 项目名称
spring.application.name=photo-management-system

# Session 类型
spring.session.store-type=none

# 数据源配置
spring.datasource.url=jdbc:postgresql://172.18.30.52:5432/photoalbum?stringtype=unspecified
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Liquibase changelog
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

# 照片存储路径
photo.storage.path=uploads/photos
