spring.application.name=photo-management-system
spring.session.store-type=none

spring.datasource.url=jdbc:postgresql://172.18.30.52:5432/brn?stringtype=unspecified
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

photo.storage.path=uploads/photos
